create type public.grupo_muscular as enum ('PEITO','COSTAS','OMBROS','BICEPS','TRICEPS','PERNAS','GLUTEOS','ABDOMEN','CARDIO','OUTROS');
create type public.status_execucao as enum ('EM_ANDAMENTO','CONCLUIDA','CANCELADA');
create type public.tipo_despesa as enum ('FIXA','VARIAVEL');
create type public.periodicidade as enum ('MENSAL');

create table public.perfis (id uuid primary key references auth.users(id) on delete cascade, nome text not null check(length(nome) between 1 and 120), criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now());
create table public.exercicios (id uuid primary key default gen_random_uuid(), usuario_id uuid not null references auth.users(id) on delete cascade default auth.uid(), nome text not null check(length(nome) between 2 and 120), grupo_muscular public.grupo_muscular not null, ativo boolean not null default true, criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now());
create table public.treinos (id uuid primary key default gen_random_uuid(), usuario_id uuid not null references auth.users(id) on delete cascade default auth.uid(), nome text not null check(length(nome) between 1 and 80), descricao text, ativo boolean not null default true, criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now());
create table public.exercicios_treino (id uuid primary key default gen_random_uuid(), usuario_id uuid not null references auth.users(id) on delete cascade default auth.uid(), treino_id uuid not null references public.treinos(id) on delete cascade, exercicio_id uuid not null references public.exercicios(id) on delete restrict, ordem smallint not null check(ordem>0), series_planejadas smallint not null check(series_planejadas between 1 and 20), repeticoes_planejadas text not null, carga_sugerida numeric(10,2) check(carga_sugerida>=0), descanso_segundos smallint not null default 60 check(descanso_segundos between 0 and 3600), observacoes text, unique(treino_id,ordem));
create table public.execucoes_treino (id uuid primary key default gen_random_uuid(), usuario_id uuid not null references auth.users(id) on delete cascade default auth.uid(), treino_id uuid references public.treinos(id) on delete set null, nome_treino text not null, status public.status_execucao not null default 'EM_ANDAMENTO', iniciada_em timestamptz not null default now(), concluida_em timestamptz, observacoes text, check(concluida_em is null or concluida_em>=iniciada_em));
create table public.series_executadas (id uuid primary key default gen_random_uuid(), usuario_id uuid not null references auth.users(id) on delete cascade default auth.uid(), execucao_id uuid not null references public.execucoes_treino(id) on delete cascade, exercicio_id uuid references public.exercicios(id) on delete set null, nome_exercicio text not null, ordem_exercicio smallint not null, numero_serie smallint not null check(numero_serie>0), repeticoes smallint not null check(repeticoes>=0), carga numeric(10,2) not null check(carga>=0), volume numeric(14,2) generated always as (carga*repeticoes) stored, concluida_em timestamptz not null default now(), unique(execucao_id,ordem_exercicio,numero_serie));
create table public.categorias_financeiras (id uuid primary key default gen_random_uuid(), usuario_id uuid not null references auth.users(id) on delete cascade default auth.uid(), nome text not null check(length(nome) between 2 and 80), cor text, padrao boolean not null default false, ativa boolean not null default true, criado_em timestamptz not null default now(), unique(usuario_id,nome));
create table public.despesas_recorrentes (id uuid primary key default gen_random_uuid(), usuario_id uuid not null references auth.users(id) on delete cascade default auth.uid(), categoria_id uuid not null references public.categorias_financeiras(id) on delete restrict, descricao text not null, valor numeric(12,2) not null check(valor>0), inicio date not null, periodicidade public.periodicidade not null default 'MENSAL', ativo boolean not null default true, criado_em timestamptz not null default now());
create table public.despesas (id uuid primary key default gen_random_uuid(), usuario_id uuid not null references auth.users(id) on delete cascade default auth.uid(), categoria_id uuid not null references public.categorias_financeiras(id) on delete restrict, recorrencia_id uuid references public.despesas_recorrentes(id) on delete set null, descricao text not null check(length(descricao) between 2 and 160), valor numeric(12,2) not null check(valor>0), data date not null default current_date, tipo public.tipo_despesa not null, observacao text, criado_em timestamptz not null default now(), unique(recorrencia_id,data));

create index exercicios_usuario_ativos_idx on public.exercicios(usuario_id,ativo,nome);
create index treinos_usuario_ativos_idx on public.treinos(usuario_id,ativo,criado_em desc);
create index exercicios_treino_treino_idx on public.exercicios_treino(treino_id,ordem);
create index execucoes_usuario_data_idx on public.execucoes_treino(usuario_id,iniciada_em desc);
create index series_exercicio_data_idx on public.series_executadas(usuario_id,exercicio_id,concluida_em desc);
create index despesas_usuario_data_idx on public.despesas(usuario_id,data desc);
create index despesas_categoria_data_idx on public.despesas(usuario_id,categoria_id,data desc);
create index recorrencias_ativas_idx on public.despesas_recorrentes(usuario_id,inicio) where ativo;

-- FKs compostas impedem associação horizontal a objetos de outro usuário.
alter table public.exercicios add constraint exercicios_id_usuario_unico unique(id,usuario_id);
alter table public.treinos add constraint treinos_id_usuario_unico unique(id,usuario_id);
alter table public.execucoes_treino add constraint execucoes_id_usuario_unico unique(id,usuario_id);
alter table public.categorias_financeiras add constraint categorias_id_usuario_unico unique(id,usuario_id);
alter table public.despesas_recorrentes add constraint recorrencias_id_usuario_unico unique(id,usuario_id);
alter table public.exercicios_treino add constraint exercicio_treino_treino_proprio foreign key(treino_id,usuario_id) references public.treinos(id,usuario_id) on delete cascade;
alter table public.exercicios_treino add constraint exercicio_treino_exercicio_proprio foreign key(exercicio_id,usuario_id) references public.exercicios(id,usuario_id) on delete restrict;
alter table public.series_executadas add constraint serie_execucao_propria foreign key(execucao_id,usuario_id) references public.execucoes_treino(id,usuario_id) on delete cascade;
alter table public.despesas_recorrentes add constraint recorrencia_categoria_propria foreign key(categoria_id,usuario_id) references public.categorias_financeiras(id,usuario_id) on delete restrict;
alter table public.despesas add constraint despesa_categoria_propria foreign key(categoria_id,usuario_id) references public.categorias_financeiras(id,usuario_id) on delete restrict;
alter table public.despesas add constraint despesa_recorrencia_propria foreign key(recorrencia_id,usuario_id) references public.despesas_recorrentes(id,usuario_id) on delete set null (recorrencia_id);

alter table public.perfis enable row level security; alter table public.exercicios enable row level security; alter table public.treinos enable row level security; alter table public.exercicios_treino enable row level security; alter table public.execucoes_treino enable row level security; alter table public.series_executadas enable row level security; alter table public.categorias_financeiras enable row level security; alter table public.despesas_recorrentes enable row level security; alter table public.despesas enable row level security;
do $$ declare t text; begin foreach t in array array['perfis','exercicios','treinos','exercicios_treino','execucoes_treino','series_executadas','categorias_financeiras','despesas_recorrentes','despesas'] loop execute format('create policy "proprietario seleciona %1$s" on public.%1$I for select to authenticated using ((select auth.uid()) = %2$I)',t,case when t='perfis' then 'id' else 'usuario_id' end); execute format('create policy "proprietario insere %1$s" on public.%1$I for insert to authenticated with check ((select auth.uid()) = %2$I)',t,case when t='perfis' then 'id' else 'usuario_id' end); execute format('create policy "proprietario atualiza %1$s" on public.%1$I for update to authenticated using ((select auth.uid()) = %2$I) with check ((select auth.uid()) = %2$I)',t,case when t='perfis' then 'id' else 'usuario_id' end); execute format('create policy "proprietario exclui %1$s" on public.%1$I for delete to authenticated using ((select auth.uid()) = %2$I)',t,case when t='perfis' then 'id' else 'usuario_id' end); end loop; end $$;

grant usage on schema public to authenticated; grant select,insert,update,delete on all tables in schema public to authenticated;
